import fetch from "node-fetch";
import dotenv from "dotenv";

dotenv.config();

// CORRECT Model ID for 2026
const MODEL_ID = "gemini-3-flash-preview";
const REQUEST_TIMEOUT_MS = Number(process.env.GEMINI_TIMEOUT_MS ?? 20000);

const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
  throw new Error("API Key not found. Please check your .env file.");
}

export async function askGemini3(prompt: string) {
  // 1. New Endpoint Format (v1beta)
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_ID}:generateContent?key=${API_KEY}`;

  // 2. New Body Format (contents -> parts -> text)
  const body = {
    contents: [
      {
        parts: [{ text: prompt }]
      }
    ]
  };

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini 3 API Error: ${response.status} - ${errorText}`);
    }

    const data: any = await response.json();

    // 3. New Response Parsing Logic
    const parts = data?.candidates?.[0]?.content?.parts;
    const textOutput = Array.isArray(parts)
      ? parts
          .map((part: any) =>
            typeof part?.text === "string" ? part.text : "",
          )
          .join("")
          .trim()
      : "";

    if (!textOutput) {
      throw new Error(
        `No response generated by Gemini (possibly blocked by safety settings). Raw: ${JSON.stringify(data).slice(0, 500)}`,
      );
    }

    return textOutput;
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") {
      throw new Error(
        `Gemini request timed out after ${REQUEST_TIMEOUT_MS}ms`,
      );
    }
    throw err instanceof Error
      ? err
      : new Error("Unknown Gemini client error");
  } finally {
    clearTimeout(timeout);
  }
}
